#!/bin/bash
# run_gui.sh — Launcher for the Divoom Desktop Control Center.
#
# On macOS we launch via Divoom.app (generated by scripts/make_app_bundle.sh) so
# the app is its own TCC "responsible process" with a Bluetooth usage description
# in its Info.plist. Without that, macOS CRASHES the process the first time it
# touches CoreBluetooth (TCC_CRASHING_DUE_TO_PRIVACY_VIOLATION) instead of
# showing the "Allow Bluetooth" dialog. The .app makes scanning/connecting work.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "${SCRIPT_DIR}"

echo "[ ==> ] Starting Divoom Desktop Control Center..."

if [[ "$(uname -s)" == "Darwin" ]]; then
    # (Re)build the bundle so its baked python/repo paths are current, then open
    # it via LaunchServices (which makes the .app the TCC responsible process).
    bash scripts/make_app_bundle.sh >/dev/null
    echo "[ ==> ] Launching Divoom.app (Bluetooth-entitled)..."
    open ./Divoom.app
    echo "[ Ok  ] Launched. First Scan prompts for Bluetooth permission — grant it once."
else
    # Linux / other: no TCC, run the GUI directly.
    python3 divoom_gui/gui_main.py
    echo "[ Ok  ] Divoom Desktop Controller closed."
fi
