#!/usr/bin/env bash
# make_app_bundle.sh — generate Divoom.app (macOS) so the app is its own TCC
# "responsible process" with a Bluetooth usage description in its Info.plist.
#
# WHY: macOS crashes a process (TCC_CRASHING_DUE_TO_PRIVACY_VIOLATION) the first
# time it touches CoreBluetooth if the responsible bundle's Info.plist lacks
# NSBluetoothAlwaysUsageDescription. Running the GUI from a bare `python3` makes
# the launching terminal the responsible process; launching this .app makes the
# .app responsible — and it DECLARES the Bluetooth usage, so macOS shows the
# normal "Allow Bluetooth" dialog and BLE works (in the GUI AND the daemon it
# spawns). The bundle bakes absolute paths, so it's generated, not committed.
#
# Usage:  ./scripts/make_app_bundle.sh            (writes ./Divoom.app)
#         open Divoom.app
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
APP="${REPO_ROOT}/Divoom.app"
PYTHON="$(command -v python3)"
BT_DESC="Divoom Control uses Bluetooth to discover and control your Divoom pixel display."
AE_DESC="Divoom Control reads the now-playing track from Music and Spotify to show album art on your screen."

if [[ "$(uname -s)" != "Darwin" ]]; then
  echo "make_app_bundle.sh is macOS-only (the .app bundle is a macOS TCC artifact)." >&2
  exit 1
fi

echo "Building ${APP}"
echo "  python: ${PYTHON}"
rm -rf "${APP}"
mkdir -p "${APP}/Contents/MacOS"

# ── Info.plist (declares the Bluetooth usage so macOS prompts instead of crashing) ──
cat > "${APP}/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleName</key>                       <string>Divoom</string>
    <key>CFBundleDisplayName</key>                <string>Divoom Control</string>
    <key>CFBundleIdentifier</key>                 <string>com.divoom.control</string>
    <key>CFBundleExecutable</key>                 <string>Divoom</string>
    <key>CFBundlePackageType</key>                <string>APPL</string>
    <key>CFBundleShortVersionString</key>         <string>1.0</string>
    <key>CFBundleVersion</key>                    <string>1</string>
    <key>LSMinimumSystemVersion</key>             <string>11.0</string>
    <key>NSHighResolutionCapable</key>            <true/>
    <key>NSBluetoothAlwaysUsageDescription</key>  <string>${BT_DESC}</string>
    <key>NSBluetoothPeripheralUsageDescription</key><string>${BT_DESC}</string>
    <key>NSAppleEventsUsageDescription</key>      <string>${AE_DESC}</string>
</dict>
</plist>
PLIST

# ── launcher (runs the GUI under the bundle; absolute paths for the minimal
#    LaunchServices environment) ──
cat > "${APP}/Contents/MacOS/Divoom" <<LAUNCH
#!/bin/bash
# Auto-generated by scripts/make_app_bundle.sh — do not edit.
cd "${REPO_ROOT}"
exec "${PYTHON}" divoom_gui/gui_main.py "\$@"
LAUNCH
chmod +x "${APP}/Contents/MacOS/Divoom"

# Make LaunchServices pick up the fresh bundle + Info.plist.
touch "${APP}"
/usr/bin/plutil -lint "${APP}/Contents/Info.plist" >/dev/null && echo "Info.plist OK"

echo "Done. Launch with:  open '${APP}'"
echo "First Scan will prompt for Bluetooth permission (grant it once)."
