from .base import DivoomCommand
from .system import System
from .alarm import AlarmMemorial
from .game import Game
from .light import Light
from .music import Music
from .sleep import Sleep
from .timeplan import Timeplan
from .tool import Tool
from .constants import *
