//! Byte-for-byte parity of the Rust framing against the Python reference.
//!
//! Vectors are generated by `native-port/gen_framing_vectors.py` from
//! `divoom_lib/framing.py` (the authoritative source) and committed as
//! `framing_vectors.json`. Regenerate them whenever the Python framing changes;
//! this test then pins the new behavior. If Python and Rust disagree on a single
//! byte, the corresponding case fails with both hex strings.

use divoomd::framing::*;
use serde_json::Value;
use std::fs;

fn vectors() -> Value {
    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/framing_vectors.json");
    let raw = fs::read_to_string(path)
        .unwrap_or_else(|e| panic!("read {path}: {e} (run native-port/gen_framing_vectors.py)"));
    serde_json::from_str(&raw).unwrap()
}

fn hex_to_bytes(s: &str) -> Vec<u8> {
    (0..s.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&s[i..i + 2], 16).unwrap())
        .collect()
}

fn to_hex(b: &[u8]) -> String {
    b.iter().map(|x| format!("{x:02x}")).collect()
}

fn as_u8_vec(v: &Value) -> Vec<u8> {
    v.as_array()
        .unwrap()
        .iter()
        .map(|x| x.as_u64().unwrap() as u8)
        .collect()
}

#[test]
fn encode_basic_matches_python() {
    for c in vectors()["encode_basic"].as_array().unwrap() {
        let payload = as_u8_vec(&c["payload"]);
        let escape = c["escape"].as_bool().unwrap();
        let got = encode_basic_payload(&payload, escape);
        assert_eq!(
            to_hex(&got),
            c["out"].as_str().unwrap(),
            "encode_basic(payload={payload:?}, escape={escape})"
        );
    }
}

#[test]
fn encode_ios_le_matches_python() {
    for c in vectors()["encode_ios_le"].as_array().unwrap() {
        let payload = as_u8_vec(&c["payload"]);
        let packet = c["packet"].as_u64().unwrap() as u32;
        let got = encode_ios_le_payload(&payload, packet).expect("non-empty payload");
        assert_eq!(
            to_hex(&got),
            c["out"].as_str().unwrap(),
            "encode_ios_le(payload={payload:?}, packet={packet})"
        );
    }
}

#[test]
fn parse_ios_le_matches_python() {
    for c in vectors()["parse_ios_le"].as_array().unwrap() {
        let input = hex_to_bytes(c["in"].as_str().unwrap());
        let got = parse_ios_le_notification(&input);
        match (&got, &c["result"]) {
            (None, Value::Null) => {}
            (Some(n), expected) if !expected.is_null() => {
                assert_eq!(n.command_id as u64, expected["command_id"].as_u64().unwrap(), "cmd for {}", c["in"]);
                assert_eq!(to_hex(&n.payload), expected["payload"].as_str().unwrap(), "payload for {}", c["in"]);
                assert_eq!(n.packet_number as u64, expected["packet_number"].as_u64().unwrap(), "pkt for {}", c["in"]);
                assert_eq!(n.checksum as u64, expected["checksum"].as_u64().unwrap(), "cksum for {}", c["in"]);
            }
            _ => panic!("parse_ios_le mismatch for {}: rust={:?} python={}", c["in"], got, c["result"]),
        }
    }
}

#[test]
fn parse_basic_matches_python() {
    for c in vectors()["parse_basic"].as_array().unwrap() {
        let mut buf = hex_to_bytes(c["in"].as_str().unwrap());
        let msgs = parse_basic_protocol_frames(&mut buf);

        let expected = c["messages"].as_array().unwrap();
        assert_eq!(msgs.len(), expected.len(), "message count for {}", c["in"]);
        for (got, exp) in msgs.iter().zip(expected) {
            assert_eq!(got.command_id as u64, exp["command_id"].as_u64().unwrap(), "cmd for {}", c["in"]);
            assert_eq!(to_hex(&got.payload), exp["payload"].as_str().unwrap(), "payload for {}", c["in"]);
        }
        // the drained buffer must equal Python's returned remainder
        assert_eq!(to_hex(&buf), c["remainder"].as_str().unwrap(), "remainder for {}", c["in"]);
    }
}
